openapi: 3.0.0
info:
  title: API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  /cql/library:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Cql'
                type: array
          description: OK
      summary: Get cql from the library
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cql'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cql'
          description: Created
      summary: Add a new cql to the library
components:
  schemas:
    Cql:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        content:
          type: string
        createdat:
          format: date-time
          type: string
        createdby: {}
        lastEditedAt:
          format: date-time
          type: string
        lastEditedBy: {}
        commitId:
          type: string
      type: object
    User:
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        createdat:
          format: date-time
          type: string
      type: object
