/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package myapi

import (
	"time"
)

type Cql struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Content string `json:"content,omitempty"`

	Createdat time.Time `json:"createdat,omitempty"`

	Createdby *interface{} `json:"createdby,omitempty"`

	LastEditedAt time.Time `json:"lastEditedAt,omitempty"`

	LastEditedBy *interface{} `json:"lastEditedBy,omitempty"`

	CommitId string `json:"commitId,omitempty"`
}
