openapi: 3.0.0
info:
  title: API
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /cql/library:
    get:
      summary: Get cql from the library
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cql'
    post:
      summary: Add a new cql to the library 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cql'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cql'
components: 
  schemas:
    Cql:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        content:
          type: string
        createdat: 
          type: string
          format: date-time
        createdby: 
          type: #/components/schemas/User
        lastEditedAt: 
          type: string
          format: date-time
        lastEditedBy:
          type: #/components/schemas/User
        commitId:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        createdat:
          type: string
          format: date-time